name: Deploy-app

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [frontend/**]
jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: frontend
  
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: SETUP
      uses: actions/setup-node@v3

    - name: Install dependecies
      run: npm ci

    - name: Build React
      env:
        REACT_APP_SERVER_URL: http://localhost:5000
      run: npm run build
