name: Deploy-server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [server/**]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    # runs actions on server directory
    defaults:
      run:
        working-directory: server

    # # Add "id-token" with the intended permissions.
    # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with: 
          workload_identity_provider: 'projects/300870622899/locations/global/workloadIdentityPools/chat-clone/providers/github'
          service_account: 'github@chat-clone-86502.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: TEST AUTH
        run: gcloud config get project

      # - name: SETUP 
      #   uses: actions/setup-node@v3

      # - name: Install dependecies
      #   run: npm ci
