name: Deploy-server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: server

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SETUP 
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependecies
        run: npm ci
