name: Deploy-prod

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          path: server
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependecies
        working-directory: ./server
        run: npm ci
        

      - name: checkout react repo
        uses: actions/checkout@v3
        with:
          path: frontend
          fetch-depth: 0

      - name: setup react repo
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependecies
        run: npm ci

      - name: Build React
        env:
          REACT_APP_SERVER_URL: http://localhost:5000
        working-directory: ./frontend
        run: npm run build
